# Generated by Django 3.2.5 on 2022-02-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='distribucion',
            old_name='fecha_distribucion',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='distribucion',
            name='analista_distribucion',
        ),
        migrations.AddField(
            model_name='distribucion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_creacion_distribucion', to='custodia.profile'),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_distribucion', to='custodia.profile'),
        ),
    ]
