# Generated by Django 3.2.5 on 2022-02-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0002_auto_20220215_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.tipooperacion'),
        ),
    ]
