# Generated by Django 3.2.5 on 2022-02-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0003_alter_distribucion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empate',
            name='empatado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='recibido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empate',
            name='distribucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.distribucion'),
        ),
        migrations.AlterField(
            model_name='empate',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('E', 'Empatado'), ('O', 'Observado')], max_length=5, null=True),
        ),
    ]
