# Generated by Django 3.2.5 on 2022-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0004_auto_20220215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empate',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Empatado', 'Empatado'), ('Observado', 'Observado')], max_length=10, null=True),
        ),
    ]
