# Generated by Django 3.2.5 on 2022-02-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0005_alter_empate_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribucion', to='custodia.desembolsos'),
        ),
        migrations.AlterField(
            model_name='empate',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Empatado', 'Empatado'), ('Observado', 'Observado')], max_length=20, null=True),
        ),
    ]
