# Generated by Django 3.2.5 on 2022-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0006_auto_20220215_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
