# Generated by Django 3.2.5 on 2022-02-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0007_auto_20220220_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='apertura',
            name='bloque',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
