# Generated by Django 3.2.5 on 2022-02-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0008_apertura_bloque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apertura',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_apertura', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='apertura',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_apertura', to='custodia.profile'),
        ),
    ]
