# Generated by Django 3.2.5 on 2022-02-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custodia", "0009_auto_20220220_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apertura",
            name="codigo_cliente",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
