# Generated by Django 3.2.5 on 2022-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0013_auto_20220221_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='levantamientos',
            name='sucursal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
