# Generated by Django 3.2.5 on 2022-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0014_levantamientos_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='fecha_observación',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
