# Generated by Django 3.2.5 on 2022-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0015_auto_20220222_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levantamientos',
            name='caja',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='carpeta',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
