# Generated by Django 3.2.5 on 2022-02-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0016_auto_20220224_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobre',
            old_name='ultima_modificacion',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='sobre',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_sobre', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_creacion_sobre', to='custodia.profile'),
        ),
    ]
