# Generated by Django 3.2.5 on 2022-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0017_auto_20220224_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='codigo',
            field=models.PositiveBigIntegerField(),
        ),
    ]
