# Generated by Django 3.2.5 on 2022-02-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0018_alter_sobre_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='sobre',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='sobre',
            field=models.ManyToManyField(blank=True, null=True, to='custodia.Sobre'),
        ),
    ]
