# Generated by Django 3.2.5 on 2022-02-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custodia', '0019_auto_20220224_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.BigIntegerField(blank=True, max_length=254, null=True)),
                ('email_politicas', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_liquidaciones', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_jefe_custodia', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_la_paz', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_el_alto', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_oruro', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_potosi', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_cochabamba', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_sucre', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_tarija', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_pando', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_beni', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_santa_cruz', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
