# Generated by Django 3.2.5 on 2022-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0020_auto_20220225_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='caja',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
