# Generated by Django 3.2.5 on 2022-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0021_alter_parametro_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='sobre',
            field=models.ManyToManyField(blank=True, to='custodia.Sobre'),
        ),
    ]
