# Generated by Django 3.2.5 on 2022-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0023_empate_tiempo_empate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empate',
            name='tiempo_empate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
