# Generated by Django 3.2.5 on 2022-02-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0024_alter_empate_tiempo_empate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_desembolso', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_desembolso', to='custodia.profile'),
        ),
    ]
