# Generated by Django 3.2.5 on 2022-02-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0026_auto_20220228_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apertura',
            name='sobre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.correspondencia'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.desembolsos'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_contrato', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='usuario_modificacion_empate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_mod_contrato_empate', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='usuario_modificacion_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_mod_contrato_legal', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_recepcion_correspondencia', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_envio_correspondencia', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='analista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuido_a', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_distribucion', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_distribucion', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='documentossueltos',
            name='sobre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.correspondencia'),
        ),
        migrations.AlterField(
            model_name='empate',
            name='usuario_empate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_empate', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.desembolsos'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_inmueble', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_inmueble', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='itemobservacion',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.subcategoriaobservacion'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_levantamientos', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.desembolsos'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='enviado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_levantamientos_formulario', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_solicitante', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_levantamiento', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='levantamientos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_levantamiento', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.categoriaobservacion'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='empate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.empate'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='observacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.itemobservacion'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='sub_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.subcategoriaobservacion'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='usuario_observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_observacion', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='usuario_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_revision', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='sobre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.correspondencia'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_poliza', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_poliza', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='custodio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario_custodio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_custodio', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_prestamo', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_sobre', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_sobre', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='subcategoriaobservacion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.categoriaobservacion'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='analista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_tarea', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_tarea', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='tipogarantia',
            name='hipotecario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.inmueble'),
        ),
        migrations.AlterField(
            model_name='tipogarantia',
            name='vehicular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.desembolsos'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_creacion_vehiculo', to='custodia.profile'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificacion_vehiculo', to='custodia.profile'),
        ),
    ]
