# Generated by Django 3.2.5 on 2022-02-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0027_auto_20220228_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoGarantia',
        ),
    ]
