# Generated by Django 3.2.5 on 2022-03-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0029_correspondencia_documento_suelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custodia.desembolsos'),
        ),
    ]
