# Generated by Django 3.2.5 on 2022-03-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0030_alter_distribucion_desembolso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
