# Generated by Django 3.2.5 on 2022-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0032_auto_20220304_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='reg_testimonio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
