# Generated by Django 3.2.5 on 2022-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0033_alter_contratos_reg_testimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Recibido', 'Recibido'), ('Distribuido', 'Distribuido'), ('Empatado', 'Empatado'), ('Observado', 'Observado'), ('Desestimada', 'Desestimada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empate',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Empatado', 'Empatado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank=True, choices=[('Asignado', 'Asignado'), ('Completado', 'Completado')], max_length=100, null=True),
        ),
    ]
