version: 1
logging:
  formatters:
    brief:
      format: "%(message)s"
    default:
      format: "%(asctime)s %(levelname)-8s [%(name)s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG

  root:
    handlers: [console]
    level: WARN
  loggers:
    app:
      level: DEBUG
